name: dependent job example

on:
  push:
    branches:
      - main

jobs:
  Job_1:
    runs-on: ubuntu-latest
    outputs:
      my_output: $ {{ steps.display.outputs.output }}

    steps:
      - id: display
        name: Run for context
        run:
          echo "output=This as an output" >> $GITHUB.OUTPUT

  Job_2:
    runs-on: ubuntu-latest
    needs: Job_1

    steps:
      - name: Print output of job 1
        run: |
          echo "Final Output: {{ needs.Job_1.outputs.my_outputs }}