name: Run github context examples

on:
  push 
   branches:
    - main

jobs:
  Run_Context:
    runs-on: ubuntu-latest

    steps:
      - name: example 1
        run: |
          echo "this is my action, $MY_ACTION"
          echo "this is my actor, $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}

